### ISSUE TITLE
How to increase TAD number for small plant genome(400Mb)?

### ISSUE THREAD

**Issue by liufuyan2016** [wbaopaul/GMAP#10]
How to increase TAD number for small plant genome(400Mb)?Could you help me how to set which parameters?

**Comment by wbaopaul** [comment]
@liufuyan2016  Maybe you can try to set min_d to 10 (default is 25) and max_d to 40 (default 100) for example; or make t1thr smaller 0.4 for instance (default 0.5). Hope it works for you.
