### ISSUE TITLE
HiC-Pro output

### ISSUE THREAD

**Issue by BenxiaHu** [wbaopaul/GMAP#12]
Hi,
  Does rGMAP accept the iced or raw results generated by HiC-Pro?
  Based on the document of rGMAP, index_obj should be 40000_abs.bed, while hic_obj should be the 40000_iced.matrix. However, I am not sure whether what I thought is right.
Thanks in advance.
best,
Benxia

**Comment by wbaopaul** [comment]
You are right.  You can use original matrix as well, but it's better to use ice normalized matrix.

**Comment by BenxiaHu** [comment]
Thanks for your reply.
the 40000_iced.matrix is the normalized matrix.  However, the 40000_abs.bed is the a genomic coordinate index file. HiC-Pro did not generate the normalized genomic coordinate index file.
Best,
Benxia

**Comment by wbaopaul** [comment]
The two coordinate index files are the same. You only normalize count matrix, not the coordinates.

**Comment by BenxiaHu** [comment]
okay. thanks.
