### ISSUE TITLE
output insulation score

### ISSUE THREAD

**Issue by BenxiaHu** [wbaopaul/GMAP#14]
recently, we checked the original code for rGMAP, we found that the rGMAP did calculate the `insulation score`. But the rGMAP did not return that.
Do you know how to obtain the `insulation score`?
![image](https://user-images.githubusercontent.com/12387462/65880526-82427780-e3c4-11e9-9e72-7af95a3fcaa1.png)
Best,

**Comment by wbaopaul** [comment]
It's hard to output those intermediate data. The fast way is to recalculate the insulation score is to use that function for each boundary in unit of bin (x), given a  n-by-n HiC matrix (pp).
