### ISSUE TITLE
TAD domain

### ISSUE THREAD

**Issue by BenxiaHu** [wbaopaul/GMAP#16]
Hi,
   Could you explian what the start and end column mean? 

![image](https://user-images.githubusercontent.com/12387462/91108148-266c8700-e645-11ea-99f7-a617d1a0e1a1.png)

**Comment by wbaopaul** [comment]
Start and end coordinates of a TAD

**Comment by BenxiaHu** [comment]
yeah.
what I meant was whether the start and end are the middle points of left bins and right bins, respectively.
As I want toconvert TAD bed format to BEDPE format, and then upload the BEDPE file into Juincebox.
Or do you have any good idea to get 2D TAD file?
Best,

**Comment by wbaopaul** [comment]
They are middle points of the bin. You may manually convert bed to bedpe.

**Comment by BenxiaHu** [comment]
thanks a lot.
