### ISSUE TITLE
Error in .M.kind(x) : not yet implemented for matrix with typeof NULL

### ISSUE THREAD

**Issue by neeteshpandey** [wbaopaul/GMAP#17]
I am trying to run this program but not able to execute due to this error, please look,
Error in .M.kind(x) : not yet implemented for matrix with typeof NULL
My matrix format is: (for single chromosome)
         n1       n2     count
1: 10369187 10394187 1299.6600
2: 10369187 10394187 2343.0500
3: 10369187 10394187   77.5128
4: 10369187 10394187  930.6630
5: 10369187 10394187 1348.6900
6: 10369187 10394187  540.2330

**Comment by wbaopaul** [comment]
Why n1 and n2 do not change for the first 6 lines? Each pair of genomic bins should not appear more than once. By the way the n1 and n2 should be given in bin id. (not the real genomic coordinate).
