### ISSUE TITLE
Set test[serror == 0] = 100L in function cal_stat

### ISSUE THREAD

**Issue by t-soehngen** [wbaopaul/GMAP#18]
Hi,
I am trying to rebuild rGMAP in python and I was wondering why you are setting all the values in test (up and down) to 100L, but at the between stat you are setting them to 0L (rGMAP_source.R line 74 ff. )
With my data that leads to the t2 candidates to be 100 which makes tad-calling rather difficult (def_tad_gmap) since neither s1 or s2 will have values greater than the threshold (line 155 ff.)
Could you help me with that problem?
Thanks!

**Comment by wbaopaul** [comment]
That's a good point. Thanks! 

line 74 (and line 86 for between stat) is just for the rare case when all contacts are 1 or all contacts are zero (thus the denominator of the test statistics is zero). I just realize that the numerator will become zero in such case as well. So it would be better to set it as 0 not 100 (Just updated it on Github).

If your t2 candidates is 100, it suggests that there are too much such kind of bins (with all  contacts are 1 or all contacts are 0 ) and the parameter d (bin size) is either too small or too large.

Hope it helps,
Best,
Wenbao

**Comment by t-soehngen** [comment]
Thanks for the explanation! I will have a look what modifying d will do.
Just one other question: Would you suggest to modify d and dp according to the resolution (e. g. with 10,000 bp min_d = 25, but with 25,000 bp min_d = 10 and so on) or could that be the culprit (since I assumed that the bp-range of the parameters should be similar and modified d and dp accordingly)?
Best
Thorben

**Comment by wbaopaul** [comment]
right. You can adjust the range of d and dp according to the resolution.
