### ISSUE TITLE
cal_insul called on binary matrix or counts?

### ISSUE THREAD

**Issue by t-soehngen** [wbaopaul/GMAP#19]
Hi,
I looked at the function tune_insulScore (source line 273f) and there you call the function cal_insul on the binary matrix(pp). When you called cal_insul before, you used the background matrix with the counts (pp1): stats1 = lapply(1:nn, cal_insul, pp1, insul_ws) source line 381. Is that done on purpose and if not, which one would be the correct matrix to use? Or were you referring to that exact thing with the comment "## without using predifined area: using intra-tad over inter-tad instead"?
Thanks for your help!
Thorben

**Comment by wbaopaul** [comment]
Using counts pp1 to calculate stats1 is to increase robustness, which was a updated version after the paper was published. Based on stats1, we can caulculate another version of local peaks. In current version, we required the original local peaks (calculated based on binary matrix) is close to the local peaks of stats1. By this, the final local peaks will be highly confident.

Hope it helps,
Wenbao
