### ISSUE TITLE
Cholmod error

### ISSUE THREAD

**Issue by lucia-ramirez** [wbaopaul/GMAP#2]
I am trying to use the package, but I am getting this error: 

Error in asMethod(object) :
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105

**Comment by wbaopaul** [comment]
I guess the format of your data might not match:
Note that the first two columns should be in the unit of bin, not the original genome coordinate.

**Comment by flay** [comment]
Hi,

I actually got the same error as above. But my first two columns are the units of bins. This is what it looks like: when loaded on R
> head(es)
   V1  V2        V3
1 301 302 10.736498
2 301 303 21.055171
3 301 304 17.131018
4 301 307  4.295697
5 301 309 27.775734
6 301 310  6.867848

This matrix is a direct output of HiC-Pro. I was wondering if you have any idea what might be the issue.

**Comment by wbaopaul** [comment]
@flay,  Hi, did you do it chromosome by chromosome? As I know, HiC-Pro output all data in one file, so you'd extract it chromosome by chromosome and re-index it for each chromosome to use rGMAP. Hope it works.

**Comment by flay** [comment]
Thanks for your response. So I separated my HiC-Pro 10kb matrix by chromosome, and tried to re-run rGMAP, but now got the following error:

> chr1.res = rGMAP(chr1, resl = 10*1000, dom_order = 2)
>>>> call TADs...
fitting ...
  |======================================================================| 100%

Killed

The script will be stuck at call TADs for about 5-10 minutes before completely killing my R session - I am not sure what caused this. Your help would be much appreciated. Thanks!

**Comment by wbaopaul** [comment]
@flay Probably lack of memory. You can try it on smaller chromosome first to make sure it's memory issue. For large chromosome, you need large memory, about 15Gb for chr1, for example. I tested rGMAP on HPC.

**Comment by flay** [comment]
So I tried chr19 which is the smallest, and use 36GB on my HPC, and still got this error:

chr19.res = rGMAP(chr19, resl = 10*1000, dom_order = 2)
Error in asMethod(object) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105

**Comment by wbaopaul** [comment]
@flay I guess you just extract the input from HiC-pro and didn't re-index the input. HiCpro indexes all chromosome together. For chr19, your maximum index number should not greater than (chr19_size/resl).

**Comment by flay** [comment]
By indexing, you mean changing the unit of column1 and 2 of HiC-Pro?
For example, the bed file output for chr19 for this matrix looks like this where the first bin is labelled as 257775. I should change that so that the first bin is 1, 2 and so forth?

chr19	0	10000	257775	0	.
chr19	10000	20000	257776	0	.
chr19	20000	30000	257777	0	.
chr19	30000	40000	257778	0	.
chr19	40000	50000	257779	0	.

Thank you for going back and forth with me for this!

**Comment by wbaopaul** [comment]
@flay , yes, 257775 should be re-index to 1 and so forth.  You can ignore those contact pairs with contact frequency 0. You just need substrate 257774 from the first two columns of contact matrix from HiCPro.

For example, your HicPro output contact matrix starts like this
257776  257778  2.2
257776  257779  2.0
...
then your input should be 
2  4  2.2
2  5  2.0
...

**Comment by ahorvath** [comment]
Dear @wbaopaul,

I tried to run the package on my data set and the first step (TAD calling) looks pretty good:  

**res = rGMAP(tt, resl = resinkb * 1000, dom_order = 2, bthr = 400)**

> res
$tads
      start      end
1   3020000  6980000
2   6980000  9860000
3   9860000 12020000
4  12020000 13580000
5  13580000 17580000
6  17580000 20260000
7  20260000 22620000
8  22620000 25540000
9  25540000 38300000
10 38300000 40300000
11 40300000 42180000
12 42180000 44420000
13 44420000 44980000
14 44980000 47980000

$hierTads
      start      end dom_order
1   3020000  6980000         1
2   6980000  9860000         1
3   9860000 12020000         1
4  12020000 13580000         1
5  13580000 17580000         1
6  17580000 20260000         1
7  20260000 22620000         1
8  22620000 25540000         1
9  25540000 38300000         1
10 38300000 40300000         1
11 40300000 42180000         1
12 42180000 44420000         1
13 44420000 44980000         1
14 44980000 47980000         1
15  3300000  6980000         2
16  9860000 10540000         2
17 10540000 12020000         2
18 12020000 13140000         2
19 13140000 13580000         2
20 40300000 41220000         2
21 41220000 42180000         2
22 42180000 43460000         2
23 43460000 44420000         2
24 44980000 46980000         2
25 46980000 47980000         2

$params
  score  d dp   t1    t2
1    79 50 10 0.75 10.78

But when trying to plot some TADs I got the following error:

 **pp = plotdom(tt, res$hierTads, 20, 25, color.th, resinkb)
Error in value[[jvseq[[jjj]]]] : subscript out of bounds
In addition: Warning messages:
1: In min(pdat$n1) : no non-missing arguments to min; returning Inf
2: In max(pdat$n1) : no non-missing arguments to max; returning -Inf**


Thanks for your help.
Attila

**Comment by wbaopaul** [comment]
@ahorvath If you change the plot region, it may help. The third and fourth parameters of the plotdom function are the start and end bin of the region you want to visual. You basically want to plot the region between the 20th and 25th bin, but probably there are no TAD in that region. Hope it works,

Best
Wenbao

**Comment by ahorvath** [comment]
Thanks, it solved. Now the plot has been generated (attached). This is a 40k res dataset (mouse chr19). Do you think that's the reason why it's so sparse or can it be improved somehow?

Thanks again, I really appreciated.

![screen shot 2018-05-15 at 11 02 00 pm](https://user-images.githubusercontent.com/351654/40083634-16cacb94-5895-11e8-8389-e9e90eb54466.png)

**Comment by wbaopaul** [comment]
@ahorvath For visualization, you can decrease the color threshold or look at a smaller region for a better visualization. Also, plotdom is not a professional visualization tool. It just gives a quick view. For calling TADs in 40kb, you can decrease some default parameter. For example, decrease bthr to 200 or 100; t1thr to 0.5; min_d = 25. The current default parameters are suggested for 10kb. 
Best,
