### ISSUE TITLE
Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105

### ISSUE THREAD

**Issue by cresswellkg** [wbaopaul/GMAP#3]
I am getting the error `Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105` whenever I try to run the rGMAP command on a 3-column sparse matrix. The matrix is 50kb resolution, chr21 (221594 x 3) and I am running it on a computer with 64GB of RAM so I do not think size should be an issue.

**Comment by wbaopaul** [comment]
@cresswellkg  I guess the first two columns are not in unit of bin; you can simply divide them by 50000 and floor/ceiling them. You can take a look the package attached example data:  head(hic_rao_IMR90_chr15).  Hope it solves your problem.

**Comment by will-NYGC** [comment]
I had this same problem and I am sure I am using bins in columns 1 and 2 as I am taking the output files from the HiC-Pro pipeline. I'm doing this at 20 and 40kb resolution and it seems when the bin counts get to a certain magnitude I get this error (the first set of chromosomes run fine). It seems like rGMAP is using the bin number and resolution to infer the coordinate of the called TADs but assumes the bins for EACH chromosome start with 1 where as the standard format for Hi-CPro is a 3 column matrix file that does not reset to 1 for each chromosome. I wonder if @cresswellkg is doing similar. I have been able to very simply get around this by shifting the bin counts to start at 1 for each chrom. In fact, this is preferred as it seems the inferred genomic coordinates would then beproperly reported as well. perhaps you could allow for passing an object that defines genomic coordinates of bins as this is also produced by HiC-Pro?

**Comment by wbaopaul** [comment]
@will-NYGC  Thanks for pointing out this issue. You are right. The start bin should be 1 for each chromosome. I did the same way as you when I using rGMAP from HiC-Pro index output.  I will update rGMAP to allow input in the format of output of HiC-Pro.

**Comment by wbaopaul** [comment]
rGMAP was updated to allow input compatible with HiC-Pro style Hi-C matrix and index file.

**Comment by ahorvath** [comment]
On which platform did you test the new version with HiC-Pro support?
I got error both on Ubuntu and Mac when trying to install:

Ubuntu:
Error: package or namespace load failed for ‘rGMAP’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/rGMAP/libs/rGMAP.so':
  /usr/local/lib/R/site-library/rGMAP/libs/rGMAP.so: undefined symbol: R_ContinueUnwind

Mac:
** testing if installed package can be loaded
Error: package or namespace load failed for ‘rGMAP’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rGMAP/libs/rGMAP.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rGMAP/libs/rGMAP.so, 6): no suitable image found.  Did find:
	/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rGMAP/libs/rGMAP.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03
	/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rGMAP/libs/rGMAP.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03

Thanks in advance.

**Comment by wbaopaul** [comment]
@ahorvath  Thanks for your interest in this package. I tested the new version on linux red hat and it works well for either installing from GitHub or from source codes. Sounds you are using R/3.4; actually the new version was built on R/3.5.0.    
  
By the way, I just tested it in on Mac; it's OK to install from the source codes but failed installing from GitHub. I will work on this and let you know if I solved the issue. 

The fast solution for you is to upgrade your R and try install rGMAP from the source codes.

**Comment by ahorvath** [comment]
You were right. Updating R to 3.5.0 got it working. Thanks for your help!

**Comment by deebhar** [comment]
Hi
I am using the output from Juicer Tool **Dump** and I am getting the same error
Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105
My input looks like this
30000	30000	2121.4888
40000	40000	2385.329
80000	80000	1273.5858
110000	110000	1597.4238

Thanks in advance.

**Comment by wbaopaul** [comment]
The first two columns of your inputs should be devided by the bin_resolution:
for instance, your resolution is 10,000bp, then your input should be something like:
3, 3, 2121.4888
...

**Comment by deebhar** [comment]
Thanks. This is working.

**Comment by deebhar** [comment]
I am getting this sort of data for one of my chromosomes
0	0	1746.334
0	25000	531.5394
25000	25000	1546.4646
0	50000	252.85974
25000	50000	539.2688
50000	50000	1571.2872
0	75000	186.7743

How do I use this in GMAP to get TAD boundaries? I am using Juicer Tool Dump to convert .hic to .txt.

**Comment by wbaopaul** [comment]
The first two columns are not in unit of bin; in your case, you can simply divide them by 25000 and your input should be like:
0 0 1746.334
0 1 531.5394
1	1	1546.4646
0	2	252.85974
1	2	539.2688
2	2	1571.2872
0	5	186.7743

And specify the parameter resl=25000.

**Comment by deebhar** [comment]
Thanks for reply. What I wanted to ask in my question was that the the problem was with the 0's in first and second column. I am getting this error
Error in validObject(r) : 
  invalid class “dsTMatrix” object: all row indices (slot 'i') must be between 0 and nrow-1 in a TsparseMatrix

How should I get rid of this?

**Comment by wbaopaul** [comment]
simply add 1 to each bin index.
