### ISSUE TITLE
html vignette link not readable

### ISSUE THREAD

**Issue by hwick** [wbaopaul/GMAP#7]
The link to the html vignette sends me to a raw html file dropbox which is not human readable. Is there another way to access the vignette?

**Comment by wbaopaul** [comment]
@hwick you can download and open it by your browser, tested on Chrome and Safari.

**Comment by hwick** [comment]
When I click Download from the html's vignette page it opens in a new tab and looks like this
![image](https://user-images.githubusercontent.com/33556230/51993599-2ca47c80-247d-11e9-8fb5-ba048a547157.png). I am using Chrome and it is up to date. Also tried saving link as, but it just links back to the raw file. Is there some other way to download it in a human or browser readable format? Same result with Safari.

**Comment by hwick** [comment]
The instructions in this thread seemed to work, and from there I was able to download the document in a human/browser-readable format: https://stackoverflow.com/questions/8446218/how-to-see-an-html-page-on-github-as-a-normal-rendered-html-page-to-see-preview

**Comment by wbaopaul** [comment]
@hwick good to know it works in this way also. Actually I mean download directly the html file in the Dropbox (not the one on GitHub) and then view it in your browser, it works.

**Comment by hwick** [comment]
Ah, I see. That does seem to work. Thank you.
