### ISSUE TITLE
Error in seq.default(min_d, max_d, by = min_d) :    wrong sign in 'by' argument; problem with index file?

### ISSUE THREAD

**Issue by hwick** [wbaopaul/GMAP#8]
Hello,
I am trying to run rGMAP and running into a couple of issues. I have HiC-Pro output, so my data is a 3-column file, and I have an index file with the bin coordinates. Initially I just read.table both the 3-column data file and bin index files in as data frames, but when I ran into problems and looked at the Rao data that came in the example I saw that it was a table, so I converted it into a table (bins are ints and counts are numeric). The bin_index file is a data frame:
```
> head(matrix_table)
   n1 n2     count
1:  2  2 8910.3187
2:  2  3 2605.6324
3:  2  4  600.7668
4:  2  5  105.0681
5:  2  6  118.1301
6:  2  7  341.9669

> head(bin_index)
    V1      V2      V3 V4
1 chr1       0 1000000  1
2 chr1 1000000 2000000  2
3 chr1 2000000 3000000  3
4 chr1 3000000 4000000  4
5 chr1 4000000 5000000  5
6 chr1 5000000 6000000  6
```
First Issue:
Despite both objects being the proper format as far as I can tell, rGMAP throws an error if I use a bin_index object for the index_file:
```
> rGMAP(matrix_table, bin_index, resl=1000000)
Error in fread(index_file, select = 1:4) : 
  input= must be a single character string containing a file name, a system command containing at least one space, a URL starting 'http[s]://', 'ftp[s]://' or 'file://', or, the input data itself containing at least one \n or \r
> rGMAP(matrix_table, index_file=bin_index, resl=1000000)
```
(same error as above)

On your resource pages, I found examples of how many columns the matrix and the index files should be, but not what data structure; I could not find an example index file object to model my index_file after. Or is it really meant to be read in directly from file path?

Second issue:
If I just use the file path to the index file instead of the bin_index object, it starts to run but throws a different error. I tried looking for this error in the source code but could not find what the origin of the issue might be:
```
> rGMAP(matrix_table, index_file="/path/to/HiC-Pro/HiC-Pro_v2.11.0/hic_results/matrix/TRT/raw/1000000/TRT_1000000_abs.bed", resl=1000000)
Working on chromosome chr1 ...
>>>> call TADs...
fitting ...
  |======================================================================| 100%
Error in seq.default(min_d, max_d, by = min_d) : 
  wrong sign in 'by' argument
In addition: Warning message:
In if (class(hic_mat) == "character") { :
  the condition has length > 1 and only the first element will be used
> rGMAP(hic_mat=matrix_table, index_file="/path/to/HiC-Pro/HiC-Pro_v2.11.0/hic_results/matrix/TRT/raw/1000000/TRT_1000000_abs.bed", resl=1000000)
```
(same error as above)

I'm not sure if this is an rGMAP issue or an error from a dependancy.
Interestingly, I get the same Warning message about condition length>1 when I run your example data set, though I do not get the additional error message and it does run. Not sure if that is an issue that I need to be concerned about?

I appreciate any help/assistance you can offer.

**Comment by wbaopaul** [comment]
@hwick There was something confusing. When multiple chromosomes are used or index_file provided, specify both hic_mat and index_file as the file path.

**Comment by hwick** [comment]
@wbaopaul When putting both file names in instead of objects, I get the same error:
```
> rGMAP("/path/to/file/TRT_1000000_iced.matrix", "/path/to/file/TRT_1000000_abs.bed", resl=1000000)
>>>> call TADs...
fitting ...
  |======================================================================| 100%
Error in seq.default(min_d, max_d, by = min_d) : 
  wrong sign in 'by' argument
```
This occurs if I use index_file="path/to/file" and/or hic_mat="path/to/file" within the rGMAP function as well.

Do you have any insight as to the origin of this error and a possible solution?

**Comment by wbaopaul** [comment]
@hwick min_d and max_d were set to be 25  and 100 by default; if the length of a chromosome in bin
 is less than max_d, max_d was set to the length of the chromosome. In your case, I guess the length of some small chromosome is less than 25Mb (thus 25 bins). I never try rGMAP on hic data with resolution as low as 1Mb (I recommend try some resolution like 40kb or 10kb). I guess you can set min_d smaller (less than the length of the chromosome) if you want use 1Mb resolution data, it should work. I will fix these bugs for next update.

**Comment by hwick** [comment]
I see, that makes sense to me. I just tried this with a higher resolution data set and it is now working. Thanks!
