### ISSUE TITLE
plotdom argument is of length zero Error

### ISSUE THREAD

**Issue by hwick** [wbaopaul/GMAP#9]
Hello,
I am trying to use plotdom to visualize my TADs. The documentation for this function states that the genome start and end bins should be included. Is this the absolute start and end bins of the entire genome (1 and 154795, according to the head/tail of my HiCPro abs.bed file for resolution 20,000 bins), or just the region which the user wants to visualize? Each set of numbers I try gives the same error. How do I resolve this?:

```
> pp_TRT_20000<- plotdom("/path/to/hic_results/matrix/TRT/iced/20000/TRT_20000_iced.matrix", TADS_TRT_20000$hierTads, 1, 154795, cthr = 20, resl = 20000)
pp_TRT_20000<- plotdom("/path/to/hic_results/matrix/TRT/iced/20000/TRT_20000_iced.m
Error in if (dim(hic_dat)[1] == dim(hic_dat)[2]) hic_dat = data.table(refm_hic(hic_dat)) : 
  argument is of length zero
```

Thank you for all of your help

**Comment by hwick** [comment]
I seem to be able to avoid this error if I read the matrix into R first and put that into the plotdom function, instead of referring to its file location (this was counterintuitive since rGMAP will not take a n object and requires the file location instead). However the plot produced does not look right.

Based on the example from the manual on the Rao dataset it looks like the start and end bins do not have to be the start/end of the genome, but the part of the genome that the user wishes to plot. Is that correct? I am curious however what the best way is to visualize specific regions containing tads, since plotdom takes bin numbers for this purpose, but the TADs produced by the rGMAP function are in genomic coordinates. Is there a simple way to determine which bins correspond to which TADs when looking at whole genome data?

Attached here is the plot I was able to produce. It is using data with a 20000 bin size. I'm unsure if it is displaying correctly, as there are so many overlapping TAD lines including some at very odd angles. I thought there were only 2 layers of TADs, but this looks like a lot more:
```
> pp<-plotdom(matrix, TADS_TRT_20000$hierTads, 1, 2000, resl=20000), and look at pp$p1, I get
> pp$p2
Warning messages:
1: Removed 3 rows containing missing values (geom_segment). 
2: Removed 6 rows containing missing values (geom_segment). 
```
![image](https://user-images.githubusercontent.com/33556230/52224057-1465a080-2875-11e9-9994-cbe8003cfcee.png)

Thanks for your assistance

**Comment by wbaopaul** [comment]
@hwick currently the plotdom function does not work well when TADs are provided with multiple chromosomes. You can limited the output hierarchical TADs and the input hic_matrix to a specific chromosome (and make sure that the hic_mat is index within that chromosome, i.e., just like the example I gave using Rao et al.'s data). I will make it more consistent for next update.

**Comment by hwick** [comment]
Thanks for the response. I've figured out how to plot single chromosomes and specific regions. However the black outlines highlighting called TADs no longer plot even though TADs and subTADs were called in the regions I am plotting. I am using r 3.5.1. The only times I've been able to get it to plot these TAD outlines have been when plotting chromosome 1, but even then there is clearly something wrong with the plotting mechanism
![image](https://user-images.githubusercontent.com/33556230/52667583-30092080-2edf-11e9-998d-dce8f3678cb8.png)

**Comment by wbaopaul** [comment]
Can you provided more information of the input arguments when you calling the plotdom ? I would suggest you use part of a chromosome, not the whole chromosome, since hic data around the end region of a chromosome is usually missed.

**Comment by hwick** [comment]
here is an example:
```
pp<-plotdom(TRT_matrix, TRT_TADS$hierTads, 135380, 135579, resl=20000)
pp$p2
```

The above line will produce a visual but there are no black outlines indicating where the program has called TADs. It is representing a section of chromosome 19 (48000000-52000000). I used the HiCPro bin index file to get these coordinates to ensure I was looking within a single chromosome and not at the very ends of it. I double checked the pp$hierTads to make sure that TADs had been called in this region.

For examples of plotdom that produce many overlapping black lines, some of which are horizontal, see previous posts in this thread

**Comment by wbaopaul** [comment]
I see. The origin design of plotdom only supports n by n matrix or hic data in Rao et al.'s format, in which the data was indexed chromosome by chromosome (the first bin always starts from 1). To view region 48000000-52000000, you should set start bin, end bin as 2400 (which is 48000000/resl) and 2600, respectively. I will update plotdom function be compatible with HiCPro index file.

**Comment by wbaopaul** [comment]
I have update rGMAP to version 1.4. Both rGMAP and plotdom function were updated. They are compatible to HiCPro inputs, and support both data frame objects and text files, see help(plotdom). Users can provided the selected chromosome and the start bin and end bin of the selected chromosome.
